### ISSUE TITLE
ops.run is too ambiguous

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava-ops#29]
Let's say that you have two `math.add` Ops:
1) An `BiInplaceFirst<IO, I2>` Op
2) A `BiFunction<IO, I2, O extends IO>` Op. 
If you have the following code
```
IO in1 = ...
I2 in2 = ...
O out = ops.run(in1, in2);
```
you have no idea whether you are running the `BiInplaceFirst` or the `BiFunction`.

The solution proposed by @ctrueden is as as follows:

* Write `Functions.apply`, `Computers.compute`, `Inplaces.mutate1/2/...` that provide the same functionality of `ops.run` (i.e. being able to pass through arguments that are used to match an `Op` then run that `Op`) however will only match their type of `Op` (i.e. a call to `Functions.apply` would only call `FunctionN`s).
* Remove `ops.run`.

Questions:
* How should these new methods handle transformations? I.e. if I call `Functions.apply("math.add", ...)`, but Ops only has a `Computer` named `math.add`, what do we do?
*  There is the question of how we approach extensibility. Let's suppose that down the line a developer develops a new kind of `Op` that does not fit in any of these categories. Are they then restricted to calling `ops.findOp`? Is this sufficient?

**Comment by MarcelWiedenmann** [comment]
While I understand the motivation for the proposed solution, I could imagine that it burdens the user too much with implementation specifics (i.e., they need to know whether a given Op is a function, computer, or inplace) and makes running Ops less convenient.
Let's say, worst case, they try to run an Op "foo" which is an `Inplace3Third`, which they don't know. They would first use `Functions.apply("foo", ...)` which fails, then likewise `Computers.compute`, `Inplaces.mutate1`, and `Inplaces.mutate2`. Until they finally reach `Inplaces.mutate3`. This kind of feels like a step backwards from the nice idea of having a one-line/one-call way of running an Op that "just works".
That being said, I don't really know a better alternative (nor do I know the importance of having `ops.run` in practice. But I believe it's quite popular because of its simplicity). Intuitively, I'd maybe hardcode some kind of "operator precedence" to break ties (e.g. function > computer > inplace). However, this would a) add another layer of complexity to the matching which is _probably_ not obvious to the user and b) also isn't extensible with respect to new kinds of Ops.
Regarding a), I've said _probably_ because `ops.run` is always called like a function (`o = ops.run("foo", i1, i2, ...)`), so at least it wouldn't be too surprising if functions took precedence.

**Comment by MarcelWiedenmann** [comment]
> How should these new methods handle transformations? I.e. if I call Functions.apply("math.add", ...), but Ops only has a Computer named math.add, what do we do?

Or let's say Ops has both a computer and an inplace "math.add", then we'll have the same problem again. We probably have two (three) options here: a) don't handle transformations at all or b) break ties in some hardcoded way, e.g., have an "operator precedence" like function > computer > inplace. (Or c) leave `ops.run` as is and break ties in some hardcoded way there.)

I could imagine that a) burdens the user too much with implementation specifics (i.e., they need to know whether a given Op is a function, computer, or inplace) and makes running Ops less convenient.
Let's say, worst case, they try to run an Op "foo" which is an `Inplace3Third`, which they don't know. They would first use `Functions.apply("foo", ...)` which fails, then likewise `Computers.compute`, `Inplaces.mutate1`, and `Inplaces.mutate2`. Until they finally reach `Inplaces.mutate3`. This kind of feels like a step backwards from the nice idea of having `ops.run` as a one-line/one-call way of running an Op that "just works".
That being said, I don't really know if b) or c) would be better. They would add another layer of complexity/decision-making to the matching which is probably not obvious to the user.

**Comment by ctrueden** [comment]
> a step backwards from the nice idea of having ops.run as a one-line/one-call way of running an Op that "just works".

I think we are all on the same page about wanting it to be as easy as possible for the user to invoke an operation. But script writers need these invocations to be on _their_ terms. They will want to be able to say, e.g., `c = a + b` (function), or `a += b` (inplace), or "fill preallocated `c` data structure with the result of" `a + b`" (computer). Writing `ops.run("math.add", c, a, b)` is semantically ambiguous and will have different behavior depending on the existence of function/computer/inplace implementations and transforms between them.

A central design goal of this new iteration of ops was to _fix this undesirable ambiguity_. To do that, we cannot leave `run` the way it is. We need `ops.apply`, `ops.compute`, `ops.inplace1`, `ops.inplace2`, etc. I do not see a way around that.

> have an "operator precedence" like function > computer > inplace.

Just to rephrase from what you wrote above: I think you are talking about the case where the user calls `ops.apply("math.add", a, b)`, but no function can be matched? So then we need to rely on transformers, typically transforming either a computer or an inplace to a function on the fly, right? And the issue is: what if there is both a computer (plus `create` op) _and_ an inplace (plus `copy` op)? Right?

In that case, I agree that we need an order of precedence. Maybe inplace is preferred to computer? Although I'm not sure the performance impact will be large either way in practice.

@MarcelWiedenmann @Treiblesschorle One aspect of this work that @gselzer and I discussed that didn't make it into the description above: there could be value in having interfaces `FunctionN`, `ComputerN`, `InplaceNFirst`, `InplaceNSecond`, etc., that operate on `Object[] args`. These would be largely for use internally, so that any `Function`, `BiFunction`, `Function3`, etc., can be transformed into a `FunctionN` for the use by `ops.apply` (or `Functions.apply`... wherever we decide to implement that code).

Before I dig in my heels further on any of this, I'd like to hack on the codebase myself a bit, to make sure my perspective is realistic. @gselzer I recommend you avoid sinking much time into the op transformer logic for the moment, and focus on getting the rest of the unit tests ported, and git history cleaned up. After that, I'm happy to take a stab at reworking the `ops.run` and op transformation logic a bit along the lines discussed here, and we can then evaluate whether it looks like a step forward or not.

**Comment by gselzer** [comment]
> I think you are talking about the case where the user calls `ops.apply("math.add", a, b)`, but no function can be matched? So then we need to rely on transformers, typically transforming either a computer or an inplace to a function on the fly...

It might be helpful to define what the contract is with `ops.apply`, `ops.compute`, etc is here (it is, at least, for me). If I am understanding this correctly (@ctrueden correct me if I am wrong), but the idea here is that if you want to make sure that all of the arguments you give to the `ops.run` system are used as **inputs**, then you would call `ops.apply`. You can end up matching any Op in the system (given there is a suitable transformation), however none of your inputs will be altered. If you call `ops.compute`, then you are telling the matcher that the last element in your set of arguments should not be considered an input as far as the algorithm is concerned (i.e. in the case of `a + b = c`, writing `ops.compute(i1, i2, i3)` tells the matcher that `i3` should not contribute to the sum). etc.

**Comment by ctrueden** [comment]
@gselzer Yes, that is a valid way to think about it. From a technical perspective, `ops.apply` is asking for "any op expressible as a `Function`-like interface with `apply` method taking those particular arguments. And analogous for the others.

**Comment by MarcelWiedenmann** [comment]
> It might be helpful to define what the contract is

>  From a technical perspective, ops.apply is asking for any op expressible as a Function-like interface with apply method taking those particular arguments. And analogous for the others. "Expressible as" here means "transformable to". 

I see. This helped me get what you guys aim for. Makes perfect sense now. I was just a bit worried that we lose functionality or make functionality harder to access (since - I believe - `ops.run` was probably the most popular way of executing an Op). But thinking about those different methods in terms of contracts and allowing transformations that adhere to these contracts sounds like a great way to make things unambiguous while staying reasonable convenient.

> Just to rephrase from what you wrote above: I think you are talking about the case where the user calls ops.apply("math.add", a, b), but no function can be matched? So then we need to rely on transformers, typically transforming either a computer or an inplace to a function on the fly, right? And the issue is: what if there is both a computer (plus create op) and an inplace (plus copy op)? Right?

Yes, that's what I mean.

> there could be value in having interfaces FunctionN, ComputerN, InplaceNFirst, InplaceNSecond, etc., that operate on Object[] args

Agreed. This would make working with functions etc. of different arities way easier. So far, I've (mis)used `OpRunner` for things like that.

**Comment by ctrueden** [comment]
> So far, I've (mis)used OpRunner for things like that

Right, the main use case for `FunctionN`, `ComputerN` etc. would be to replace `OpRunner`. So you'd have a "function op runner" and a "computer op runner" which are different things. Anything transformable to a `FunctionN` can be "run" as a function (i.e. `apply`ed). And so forth for computers and inplaces. Ideally we'd keep the interfaces non-public, so that no one is tempted to code an op as a `FunctionN` directly, since that would not be type-safe.

**Comment by ctrueden** [comment]
See also #32, where we are hammering out an API that will also address this issue, but in a slicker way than what I propose above.

**Comment by gselzer** [comment]
@ctrueden this can probably be closed since #40 was merged.
