### ISSUE TITLE
Implement Contingent

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava-ops#3]
Currently, there is no interface ```Contingent``` and contingency will not be checked. In order to do it without the need for such an interface, it could be done the following way: Usually contingent switches between Ops for special kinds of inputs (e.g. 2D vs. 3D version of an Op). Hence, there could be a _meta_ Op which checks its inputs for these properties and switches between the correct version of the Ops internally.

**Comment by Treiblesschorle** [comment]
@gselzer Could you maybe add the other use cases for Contingent here that you found?

**Comment by gselzer** [comment]
Here is my compiled list of use cases currently in ImageJ-Ops for `Contingent`:
* Confirming equal dimensionality of 2+ inputs or between inputs and outputs
* Confirming equal iteration order of inputs and outputs
* Confirming non-null inputs
* Confirming non-null / otherwise suitable secondary arguments (see [`CreateKernel2D`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/create/kernel/CreateKernel2D.java) or [`ConvolveNaiveF`](https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/filter/convolve/ConvolveNaiveF.java))

As far as these go there are really two distinct categories, the categories where there might be a second `Op` that works (better) on the Parameters, which the first point definitely falls under and the last point could also. There is also the category in which we are using `Contingent` as a way of avoiding issues, which the second and third points definitely fall and the last point could as well.

**Comment by ctrueden** [comment]
We will definitely not support matching ops based on actual input arguments. Matching on types only unlocks a host of benefits.

We will use a "delegating op" pattern—i.e., an op that contingently invokes one of its op dependencies at execution time, based on characteristics of the inputs—to deal with things like "for small kernels do this, for large kernels do that."

For cases where the inputs are not appropriate—e.g. a binary function on two images and the images need to be the same size—we'll throw an exception. Because I can't come up with anything better.
