### ISSUE TITLE
Builderish pattern for calling ops

### ISSUE THREAD

**Issue by frauzufall** [scijava/scijava-ops#32]
Greetings from the KNIME Hackathon! We are discussing calling ops this way:
```
op().input(img1, img2).output(img3).compute("math.add");
img3 = op().input(img1, img2).apply("math.add");
```

**Comment by frauzufall** [comment]
An idea for optional parameters:
```
op().inputs().output().options().compute();
```

**Comment by frauzufall** [comment]
We also talked about auto completion (script editor, IntelliJ, Eclipse) and the more I think about it, the more I like the following syntax:
```
op("math.add").input(img1, img2).output(img3).compute();
```
One can easily grasp what's happening by reading the line from left to right and the auto completion might be simpler to implement than in my first example.

It can autocomplete the op name when someone types `op(`, can then check and display for this op which input parameters are allowed and, depending on if the user adds an output, suggest suitable execution strategies.

**Comment by gselzer** [comment]
Woah, this is a cool idea! How were you thinking the `OpRef`s would be built? Would the `OpService` maintain all of this input/output/Op name data and then, when a user calls `compute()`, generate a `ComputerN` (although we can probably do better and keep a mapping of number of parameters to a particular computer interface) and feed that into the matcher?

It is a little annoying that it would be a lot more verbose than the previously proposed `ops.compute("math.add", img1, img2, img3")`, but seeing as how we are gaining specificity and precision here I don't really consider this to be an issue.

Also, have you thought about what the call would look like for inplaces? We could do something like `op("math.add").input(img1, img2).ioIndex(0).mutate()` ... I don't know, my mind is still not fully awake.

One last thing, @ctrueden and I were planning on removing secondary parameters from the Ops system entirely (unless you changed your mind at Konstanz @ctrueden?) since having secondary parameters prevented us from calling ops in a more functional manner. Furthermore, you can imitate secondary parameters by writing a simple lambda.

**Comment by ctrueden** [comment]
Thanks for the feedback, @gselzer. I was working with @frauzufall today on this; here are our rough notes from earlier.

```java
// variables
I1 img1 = ...;
I2 img2 = ...;
O myResultImg = ...;

// match then execute
ops.op("math.add").inputs(img1, img2).output(myResultImg).compute();
ops.compute("math.add").inputs(img1, img2).output(myResultImg).compute();
ops.compute("math.add").inputs(img1, img2).output(myResultImg).compute();

// match only
BiComputer<I1, I2, O> op =
  ops.op("math.add").inputs(img1, img2).output(myResultImg);
// and then run it -- potentially multiple times with different inputs
op.compute(img1, img2, myResultImg);
```

What would the types of these builder things need to be? Here is our brainstorm:

```java
// computer
OpBuilderN builderN = ij.op().match("math.add")
OpBuilder2 builder2 = builderN.inputs(img1, img2)
builder2.inplace1
OpBuilder2WithOutput builder2O = builder2.output(myResultImg)
BiComputer<? super I1, ? super I2, ? extends O> computer2Op = builder2O.computer() // should we use wildcards?
builder2O.compute() // void return type
computer2Op.compute(img1, img2, myResultImg) // DOES THIS COMPILE?
OpBuilder2WithInplaceArg builder2IA = builder2.inplaceArg(i2)
BiInplace< builder1IA.op()
// Where BiInplace is a superinterface of BiInplace1 and BiInplace2.
// The BiInplace base interface needs a @NoMatch annotation so that it can't be directly matched? Or maybe we can get away with a @MaybeMutable annotation on all its params?
// Change naming of Inplace3First -> Inplace3_1; Inplace2Second -> Inplace2_2; etc.
// now it sorts correctly and Gabriel is happy. :-)

// function
BiFunction<? super I1, ? super I2, ?> function2OpObjectResult = builder2.function()
Object myNonTypedResultImg = builder2.apply()
Object myNonTypedResultImg_ = function2OpObjectResult.apply(img1, img2)
OpBuilder2WithOutputType builder2OT = builder2.outType(new Nil<O>() {})
O myResultImg = builder2OT.apply()
BiFunction<? super I1, ? super I2, ? extends O> function2OpTypedResult = builder2OT.function()
O myResultImg_ = function2OpTypedResult.apply()
```

Next steps for me right now:

* Fix up and merge #2 (which unfortunately is now out of sync, and needs cleaning up).
* Actually implement the ideas above on a new `builder-pattern` branch.

**Comment by gselzer** [comment]
@ctrueden I am sorry but I am now super confused:
`OpBuilderN builderN = ops.match("math.add")`: This `match` method is super confusing. At first I thought you were intending to match an op based on a name alone, which is crazy.  Are you just asking for all ops named `math.add`? 

What is this `OpBuilderN`? Is it a collection of `OpInfo`s? Or is it just some container that you are going to populate with inputs, output, name, etc. and that will be able to construct an `OpRef` when you call `compute()`/`op()`? And if that is the case, then what is the point of making N different `OpBuilder` classes anyways? Why not just make one `OpBuilder` class that is smart enough to say "okay, we have n inputs and the user just called my `compute` method so I know that I need to make a `Computern` `OpRef`"? Part of me feels like we (I) have created too many different types of Ops (i.e. the basic interfaces, `Generic` ops, `ComputerOp`/`BiComputerOp`/...., etc) and this will just add to our code base.

Also, I am not sure what your point is in wanting to add a `BiInplace` interface? What are you needing it for that we cannot do with `BiInplaceFirst`, `BiInplaceSecond`? (btw, I am more than happy to change the naming of the inplaces as you suggested above, those names are much better :grin:)

**Comment by ctrueden** [comment]
> Or is it just some container that you are going to populate with inputs, output, name, etc. and that will be able to construct an OpRef when you call compute()/op()?

Yes, that.

> And if that is the case, then what is the point of making N different OpBuilder classes anyways?

Because e.g. calling `builder2O.op()` needs to return a `BiComputer`. If we only had a single `OpBuilder` and it had an `op()` method, what would the return type be? It wouldn't be type-safe.

The `inputs()` and `outputs()` methods narrow the "builder type" such that when you subsequently request to execute an op—or just obtain a reference to it—it can be done in a type-safe way.

> this will just add more unneeded files to our code base.

Yes, it sucks in that we'll have another set of numbered classes, tucked away in a package (probably `org.scijava.ops.builder`). However, it's sort of a "ripple effect" of embracing the one-interface-per-arity design in the first place. I don't think we can avoid it here, if we want to have these nice type-safe builders.

> I am not sure what your point is in wanting to add a BiInplace interface?

I'm working on implementing it now... you'll see why it's needed once the code exists. :wink:

> I am more than happy to change the naming of the inplaces as you suggested above

Great—I will do that as well.

**Comment by ctrueden** [comment]
Proof of concept demonstrating functions is now on the `builder-pattern` branch. Computers and inplaces coming tomorrow.

**Comment by frauzufall** [comment]
The syntax in the tests looks good!

**Comment by ctrueden** [comment]
I have pushed a new version of `builder-pattern` which: A) reworks the computer, function and inplace interfaces to be more nicely organized; and B) adds computer support (arity 0, 1 and 2) to the `OpBuilder`. See `OpBuilderTest` for examples of what is currently supported.

Inplaces still to come soon.

**Comment by ctrueden** [comment]
@gselzer added inplaces, and I started work on a code generation scheme.

**Comment by frauzufall** [comment]
Cool! What do you mean with code generation scheme?

**Comment by ctrueden** [comment]
Same as the old ImageJ Ops, except not hooked into the Maven build. We'll just regenerate + commit by hand if we ever need to re-run code generation. That way, Eclipse will not behave as badly. See fafb957c738e3e503ae08476ae9792590c02c5f7 for the initial cut; will become more elegant as we keep hacking on it.

**Comment by gselzer** [comment]
Check out #38 for the finished product
