### ISSUE TITLE
Add more Op Utilities

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava-ops#7]
All the utility classes contained in ```org.scijava.ops.util``` should be extended with further functionality.
#### Adapt
* Add more adapters, which adapt between all functional types (e.g. TriConsumer to TriFunction).
* The above also mean that they can be added as ```OpTransformers``` to the auto transform.
 #### Computers, Functions, Inplaces
* Add convenience methods to retrieve Ops with these special types
 #### Maps
* Add Lifters for more lift types. Especially, for ImgLib2 types like ```IterableInterval``` etc.
* All the maps from __net/imagej/ops/map/Maps.java__ may be expressed that way.
* The above also mean that they can be added as ```OpTransformers``` to the auto transform.

During conversion of the Ops from the old system to the new one there may be more functional types that get added to the system. Then we should add utilities and transformers for them.

**Comment by gselzer** [comment]
It seems to me that this issue is outdated. I'll address each of the sections in the issue:

* Adapt: Not only have we adopted `adapt` Ops as a replacement to `OpTransformer`s, but we should be able to adapt between all Op types that make sense. We have `Computer` -> `Function`, `Function -> Computer`, and `Inplace -> Function` spanning all arities. @ctrueden and I have discussed numerous times why the other conversions do not make sense (see #47)

* Computers, Functions, Inplaces: We have [`OpBuilder`](https://github.com/scijava/scijava-ops/pull/38) for this.

* Maps:
  * We have a great deal of Lifters already. We can currently lift to [anything iterable](https://github.com/scijava/scijava-ops/blob/master/src/main/java/org/scijava/ops/adapt/lift/ComputerToIterables.java), which does cover `II`s. We *should* have the capability to lift to arrays (there is a separate issue for this, see #46. We also have [`RAI` lifters](https://github.com/scijava/incubator/blob/master/imagej/imagej-ops2/src/main/java/net/imagej/ops2/types/adapt/LiftComputersToRAI.java) covered, but they (along with any other lifter based on ImgLib2 types) will live in ops2.
  * We have decided to express standard mappings via `Lifters`, however whenever the mapping needs a `Shape` we have decided to use [`LoopBuilder`](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/loops/LoopBuilder.java) instead (see scijava/incubator#13)

For these reasons I will close this issue, in favor of the more specific issues mentioned above.
