### ISSUE TITLE
Add Ops.run(...)

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava-ops#8]
Currently, ```Ops.run(...)``` is not available in the system. This should be added eventually using the type reasoning supplied by the ```TypeService```.

**Comment by gselzer** [comment]
Just as an update since a lot has happened on this matter:
* We have a functional ops.run() that works on the majority of cases.
* The main source of error at this point lies in reifying generic types. Many of these can be solved using a simple `TypeExtractor` plugin, and there are folders within Scijava-ops and imagej-ops for java library and imglib/imagej `Type`s respectively. 
  * There are a few types that simply cannot be reified at runtime (see, for example, [`OutOfBoundsFactory`](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/outofbounds/OutOfBoundsFactory.java). We then parameterize these types with [`Any`](https://github.com/scijava/scijava-ops/blob/master/src/main/java/org/scijava/ops/types/Any.java), a type that is designed to theoretically match all types simultaneously. The output of `ops.run` is also an `Any`. This does, however, come with bugs (see #22).
  * Other types, like most `Op` types, can be reified but are tricky to do in practice. A partial solution to this exists in the idea of creating `GenericOp`s for each `Op` type (e.g. `GenericFunction3`). All `Op`s are wrapped into these `GenericOp`s at Op discovery time using the class/lambda itself along with its generic type, which we discover from the `Field`/class declaration.
    * This solution, sadly, does not work for lambdas that a user never formally declares as an `Op`, and in the case that a user creates a lambda that they wish to pass to `ops.run()` the user will have to wrap it into a `GenericOp` themselves with its generic type beforehand.
* There is currently no support for returning multiple outputs for multiple matched `Op`s. This was [something supported in the previous iteration](https://github.com/imagej/imagej-ops/blob/dbb03bde5b4b3a96d78d3b54020084af4ff1792f/src/main/java/net/imagej/ops/OpEnvironment.java#L952), and [there are tests that utilize this feature](https://github.com/imagej/imagej-ops/blob/dbb03bde5b4b3a96d78d3b54020084af4ff1792f/src/test/java/net/imagej/ops/geom/QuickHull3DTest.java#L63), however we have to decide if this is something that we want to support (@ctrueden, thoughts?).

**Comment by ctrueden** [comment]
We decided not to support multiple outputs anymore. (Side note, just to be clear: the multiple outputs were not for "multiple matched ops", but rather for ops with multiple declared output parameters.)

**Comment by gselzer** [comment]
Sorry, yes, this is correct @ctrueden. I forgot that I had to split this particular Op being tested in the link above into two Ops to deal with the multiple outputs, I will just have to change the name of one of the Ops. Sorry for the confusion.

**Comment by gselzer** [comment]
`ops.run()` was added [here](https://github.com/scijava/scijava-ops/commit/bce0c1f835eda4bfbff09c7f386535d62172ad3b), and then removed [here](https://github.com/scijava/scijava-ops/commit/c5cbaaf4a614c1d537fd62c6c6d5a87cbbafbb8a) in favor of the `OpBuilder` constructions (which were added [here](https://github.com/scijava/scijava-ops/pull/38)).
